return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'nvim-treesitter/nvim-treesitter'
  use 'ryanoasis/vim-devicons'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'neovim/nvim-lspconfig'
  use 'hrsh7th/nvim-cmp'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-buffer'
  use 'akinsho/toggleterm.nvim'
  use 'kyazdani42/nvim-tree.lua'
  use 'lukas-reineke/indent-blankline.nvim'
  use 'simrat39/rust-tools.nvim' 
  use 'jiangmiao/auto-pairs'
  use 'nvim-telescope/telescope-ui-select.nvim'
  use 'ahmedkhalf/project.nvim'
  use 'pocco81/truezen.nvim'
  use 'onsails/lspkind.nvim'
  use 'L3MON4D3/luasnip'
  use 'saadparwaiz1/cmp_luasnip'
  use 'hrsh7th/cmp-nvim-lua'
  use {'akinsho/bufferline.nvim', tag = "v2.*", requires = 'kyazdani42/nvim-web-devicons'}
  use 'vimwiki/vimwiki'
  use 'Pocco81/TrueZen.nvim'
  use 'preservim/vim-pencil'
  use 'junegunn/limelight.vim'
  use 'jamessan/vim-gnupg'
  use 'mfussenegger/nvim-dap'
  use 'mrjones2014/smart-splits.nvim'
  use 'saecki/crates.nvim'
  use 'folke/tokyonight.nvim'
  use 'lewis6991/gitsigns.nvim'
end)


